---
replicaCount: 1
image:
  repository: ghcr.io/naviteq/k8s-resource-simulator
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
  # fsGroup: 2000
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    memory: 512Mi

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

env:
  - name: CPU_MILLICORES
    value: '{{ (required  "Please specify CPU requests in milli-cores format!" .Values.resources.requests.cpu) | replace "m" "" }}'
  - name: MEMORY_MIB
    value: '{{ (required "Please specify Memory requests in Mi format!" .Values.resources.requests.memory ) | replace "Mi" "" }}'

volumes: []
volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
