---

name: CI (Main branch)
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@5b8826cfc79c3a060cec9b2406886a248ee23fef  # v1.20.9
    with:
      REGISTRY: ghcr.io
      DOCKER_CONTEXT: .
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release-github.yaml@5b8826cfc79c3a060cec9b2406886a248ee23fef  # v1.20.9
    needs: [docker]
    with:
      CHART_LOCATION: helm
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: naviteq/github-actions/.github/workflows/create-release.yaml@5b8826cfc79c3a060cec9b2406886a248ee23fef  # v1.20.9
    secrets: inherit
    needs:
      - docker
      - helm
