---

name: CI (Main branch)
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@main
    with:
      REGISTRY: ghcr.io
      DOCKER_CONTEXT: .
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release.yaml@main
    needs: [docker]
    with:
      CHART_LOCATION: helm
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    uses: naviteq/github-actions/.github/workflows/create-release.yaml@main
    secrets: inherit
    needs:
      - docker
      - helm
