---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+']

jobs:
  docker:
    uses: naviteq/github-actions/.github/workflows/docker-build.yaml@5b8826cfc79c3a060cec9b2406886a248ee23fef  # v1.20.9
    with:
      REGISTRY: ghcr.io
      DOCKER_CONTEXT: .
      IMAGE: ${{ github.repository }}
      USERNAME: ${{ github.actor }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}

  helm:
    uses: naviteq/github-actions/.github/workflows/helm-release-github.yaml@5b8826cfc79c3a060cec9b2406886a248ee23fef  # v1.20.9
    needs: [docker]
    with:
      chart_path: helm
      ghcr_repo: ${{ github.repository }}
      bump_version_git_branch: main
    secrets:
      GITHUB_APP_ID: ${{ secrets.NAVITEQ_GITHUB_APP_ID }}
      GITHUB_APP_KEY: ${{ secrets.NAVITEQ_GITHUB_APP_KEY }}
      token: ${{ secrets.GITHUB_TOKEN }}
